name: Build

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build.yml"
      - "include/**/*"
      - "src/**/*"
      - "test/**/*"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/build.yml"
      - "include/**/*"
      - "src/**/*"
      - "test/**/*"

concurrency:
  group: build-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  test:
    strategy:
      fail-fast: false
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout ğŸ›’
        uses: actions/checkout@v2
      - name: Intall dependencies ğŸ“¥
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgtk-3-dev libwebkit2gtk-4.1-dev libgtk-layer-shell-dev libxcb-ewmh-dev
          version: 1.0
      - name: Build ğŸ—ï¸
        run: make BUILD_PROFILE=RELEASE
      - name: Upload artifacts ğŸš€
        uses: actions/upload-artifact@v4
        with: {
          name: "tosu-overlay-${{ github.ref_name }}",
          path: build/bin/tosu-overlay
        }
