name: Build

on:
  push:
    branches: [main, gtk4]
    paths:
      - ".github/workflows/build.yml"
      - "include/**/*"
      - "src/**/*"
      - "test/**/*"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/build.yml"
      - "include/**/*"
      - "src/**/*"
      - "test/**/*"

concurrency:
  group: build-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  test:
    strategy:
      fail-fast: false
    name: Build
    runs-on: ubuntu-25.04
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2
      - name: Intall dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgtk-4-dev libwebkitgtk-6.0-dev libgtk4-layer-shell-dev
          version: 1.0
      - name: ğŸ—ï¸ Build
        run: make BUILD_PROFILE=RELEASE
      - name: ğŸš€ Upload artifacts
        uses: actions/upload-artifact@v4
        with: {
          name: "tosu-overlay-${{ github.ref_name }}",
          path: build/bin/tosu-overlay
        }
